name: Auto-Update Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Extract version from addon.xml
      id: get_version
      run: |
        VERSION=$(python3 -c "import xml.etree.ElementTree as ET; tree = ET.parse('service.cloudsync/addon.xml'); print(tree.getroot().get('version'))")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Found version: $VERSION"

        # Always build since ZIPs are ignored by git and may not exist locally
        echo "Building ZIP for version $VERSION"
        echo "SKIP_BUILD=false" >> $GITHUB_OUTPUT

    - name: Create addon ZIP and MD5
      if: steps.get_version.outputs.SKIP_BUILD == 'false'
      run: |
        # Create proper Kodi addon ZIP structure with addon folder inside
        mkdir -p temp_build/service.cloudsync
        cp -r service.cloudsync/* temp_build/service.cloudsync/

        # Remove any existing ZIP files from the copy
        find temp_build/service.cloudsync -name "*.zip" -delete
        find temp_build/service.cloudsync -name "*.md5" -delete

        # Create ZIP with proper structure (service.cloudsync/ folder inside)
        cd temp_build
        zip -r ../temp_addon.zip service.cloudsync -x "*.pyc" "*/__pycache__/*"
        cd ..

        # Create service.cloudsync directory if it doesn't exist
        mkdir -p service.cloudsync

        # Move ZIP to proper Kodi repository location
        mv temp_addon.zip service.cloudsync/service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip

        # Generate MD5 in proper location
        cd service.cloudsync
        md5sum service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip > service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip.md5
        cd ..

        # Clean up
        rm -rf temp_build

        echo "Created service.cloudsync/service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip (Kodi repository standard)"

    - name: Update addons.xml with current version
      run: |
        # Update version in addons.xml using sed
        sed -i 's/\(<addon id="service\.cloudsync"[^>]*version="\)[^"]*\(".*>\)/\1${{ steps.get_version.outputs.VERSION }}\2/' addons.xml
        echo "Updated addons.xml to version ${{ steps.get_version.outputs.VERSION }}"

    - name: Update addons.xml.md5
      run: |
        md5sum addons.xml | cut -d' ' -f1 > addons.xml.md5.temp
        echo " *addons.xml" >> addons.xml.md5.temp
        mv addons.xml.md5.temp addons.xml.md5
        echo "Updated addons.xml.md5"

    - name: Update repository.cloudsync files
      run: |
        if [ -d "repository.cloudsync" ]; then
          cp addons.xml repository.cloudsync/addons.xml
          cp addons.xml.md5 repository.cloudsync/addons.xml.md5
          echo "Updated repository.cloudsync files"
        fi

    - name: Commit and push all changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update repository for v${{ steps.get_version.outputs.VERSION }}"
          git push
          echo "Repository updated for version ${{ steps.get_version.outputs.VERSION }}"
        else
          echo "No changes to commit"
        fi

    - name: Create repository ZIP
      if: steps.get_version.outputs.SKIP_BUILD == 'false'
      run: |
        # Create repository ZIP with proper structure (repository.cloudsync/ folder inside)
        if [ -d "repository.cloudsync" ]; then
          zip -r repository.cloudsync.zip repository.cloudsync
          echo "Created repository.cloudsync.zip with proper structure"
        fi

    - name: Create GitHub Release
      if: steps.get_version.outputs.SKIP_BUILD == 'false'
      run: |
        # Check if release already exists
        if gh release view "v${{ steps.get_version.outputs.VERSION }}" >/dev/null 2>&1; then
          echo "Release v${{ steps.get_version.outputs.VERSION }} already exists, skipping creation"
        else
          # Create temporary ZIP for release (from service.cloudsync location)
          cp service.cloudsync/service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip ./

          gh release create "v${{ steps.get_version.outputs.VERSION }}" \
            service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip \
            repository.cloudsync.zip \
            --title "CloudSync v${{ steps.get_version.outputs.VERSION }}" \
            --notes "CloudSync v${{ steps.get_version.outputs.VERSION }} - New version with latest improvements and fixes."
          echo "Created release v${{ steps.get_version.outputs.VERSION }}"

          # Clean up temporary file
          rm -f service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip
        fi
      env:
        GH_TOKEN: ${{ github.token }}

