name: Auto-Update Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Extract version from addon.xml
      id: get_version
      run: |
        VERSION=$(python3 -c "import xml.etree.ElementTree as ET; tree = ET.parse('service.cloudsync/addon.xml'); print(tree.getroot().get('version'))")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Found version: $VERSION"

        # Check if ZIP already exists
        if [ -f "service.cloudsync-${VERSION}.zip" ]; then
          echo "ZIP file already exists for version $VERSION"
          echo "SKIP_BUILD=true" >> $GITHUB_OUTPUT
        else
          echo "Need to build ZIP for version $VERSION"
          echo "SKIP_BUILD=false" >> $GITHUB_OUTPUT
        fi

    - name: Create addon ZIP and MD5
      if: steps.get_version.outputs.SKIP_BUILD == 'false'
      run: |
        cd service.cloudsync
        zip -r ../service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip . -x "*.pyc" "*/__pycache__/*"
        cd ..
        md5sum service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip > service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip.md5
        echo "Created service.cloudsync-${{ steps.get_version.outputs.VERSION }}.zip"

    - name: Update addons.xml.md5
      run: |
        md5sum addons.xml | cut -d' ' -f1 > addons.xml.md5.temp
        echo " *addons.xml" >> addons.xml.md5.temp
        mv addons.xml.md5.temp addons.xml.md5
        echo "Updated addons.xml.md5"

    - name: Update repository.cloudsync files
      run: |
        if [ -d "repository.cloudsync" ]; then
          cp addons.xml repository.cloudsync/addons.xml
          cp addons.xml.md5 repository.cloudsync/addons.xml.md5
          echo "Updated repository.cloudsync files"
        fi

    - name: Commit and push all changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update repository for v${{ steps.get_version.outputs.VERSION }}"
          git push
          echo "Repository updated for version ${{ steps.get_version.outputs.VERSION }}"
        else
          echo "No changes to commit"
        fi

